# Numpy array and basics


In [ ]:
import numpy as np

py_list = [1,2,3,4,5]
print("Python list: ",py_list)

np_array = np.array([1,2,3,4,5])
print("Python array: ",np_array)

Python list:  [1, 2, 3, 4, 5]
Python array:  [1, 2, 3, 4, 5]


### Multiplying nparray vs list



In [5]:
py_list = [1,2,3,4,5]
np_array = np.array([1,2,3,4,5])
print("Python list multiplication: ",py_list*3)
print("Python array multiplication: ",np_array*2)

Python list multiplication:  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Python array multiplication:  [ 2  4  6  8 10]


# Difference between numpy array and list


#### 1.Numpy array are vectorized operation(that means a single instruction can be performed on multiple data parallely)
#### 2.Whereas, list operation are done using loops(iterations) which are really slow
#### Below, I have measured the run time for numpy vs list

In [12]:
import numpy as np
import time

size = 10**6
py_list = list(range(size))
np_array = np.arange(size)

# I want to add 1 to each number in my array
# Let's first add 1 to my python list and measure the time needed for that
start_time = time.time()
py_list = [x*2 for x in py_list]
end_time = time.time()

print("Total Time Taken by python list: ",end_time-start_time)

start_time = time.time()
np_array = np_array *2
end_time = time.time()

print("Total Time Taken by numpy array: ",end_time-start_time)

Total Time Taken by python list:  0.04517555236816406
Total Time Taken by numpy array:  0.0018181800842285156


#### Numpy uses SIMD(Single Instruction Multiple Data). So, CPU performs single instruction(i.e multiplying by 2) to every element in the array without using a loop

# Creating arrays from scratch


In [ ]:
import numpy as np
zeros = np.zeros((3,4))
print("Zeros array:\n ",zeros)

ones = np.ones((3,4))
print("Ones array:\n ",ones)

full = np.full((2,2,2),1)
print("Full : \n",full)

random = np.random.random((2,3))
print("Random Matrices:\n",(random*10))

sequence = np.arange(0,10,2)
print("Sequence Vector: ",sequence)



Zeros array:
  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array:
  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full : 
 [[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
Random Matrices:
 [[3.28836292 4.72492971 4.47224065]
 [1.29398921 4.12757979 7.42377034]]
Sequence Vector:  [0 2 4 6 8]


# Vector, Matrices and Tensor

### Vector
#### => A vector is a one-dimensional array. It has only one axis 

In [5]:
vector_1 = np.array([1,2,3])
print(vector_1)

[1 2 3]


### Matrices

### => Matrices are 2D arrays, it means they have 2 axis(rows and columns)
### => Used in ML for datasets and transformations

In [6]:
matrices_1 = np.array([[1,2,3],[4,5,6]])
print(matrices_1)

[[1 2 3]
 [4 5 6]]


### Tensors


### =>Tensors are 3D,4D and higher dimensional arrays. They are used in image processing, videos etc

In [8]:
tensor_1 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor_1)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


# UNDERSTANDING IMAGE REPRESENTATION AS A 3D TENSOR

In [ ]:
import numpy as np

image_tensor = np.array([1,2,3,4,5],dtype= np.int8)